package com.example.livescoreapidemo.dataclasses.newsdetails

data class Article(
    val additionalCategories: List<Any>,
    val authors: List<Author>,
    val body: List<Body>,
    val category: Category,
    val categoryLabel: String,
    val channels: List<Any>,
    val createdAt: String,
    val entityType: String,
    val id: String,
    val isAdsEnabled: Boolean,
    val isAdultContent: Boolean,
    val isArticleAvailable: Boolean,
    val isLive: Boolean,
    val isSensitiveContent: Boolean,
    val leagues: Any,
    val mainMedia: MainMedia,
    val origin: Any,
    val provider: String,
    val publishedAt: String,
    val publishedBy: PublishedBy,
    val publishedDate: String,
    val publishedRegions: List<Any>,
    val publishedTime: String,
    val related: Related,
    val seo: SeoX,
    val status: String,
    val subTitle: Any,
    val teams: Any,
    val title: String,
    val type: Any,
    val until: Any,
    val updatedAt: UpdatedAtX,
    val updatedAtUtc: String,
    val url: String
)